name: slack-help-bot
apiVersion: v2
home: https://github.com/hmcts/slack-help-bot
version: 0.0.1
description: Slack Help Bot
maintainers:
  - name: PlatOps Team
dependencies:
  - name: nodejs
    version: 2.3.4
    repository: "https://hmctspublic.azurecr.io/helm/v1/repo/"