# defaults are setup for the platform engineering slack workspace
slack:
  # bot_token: no default
  # app_token: no default
  report_channel: pofcc-onboarding-support
  report_channel_id: C09LE7XVCMV

jira:
  start_transition_id: 21
  done_transition_id: 41
  project: POFCC
  issue_type_name: Support
  issue_type_id: 18400
  # username: no default
  # api_token: no default
