# defaults are setup for the platform engineering slack workspace
slack:
  #bot_token: no default
  #app_token: no default
  report_channel: bot-test
  report_channel_id: C01KHKNJUKE

jira:
  start_transition_id: 21
  done_transition_id: 41
  project: SBOX
  priority_id: 4 # medium in SBOX
  issue_type_id: 10900
  #username: no default
  #password: no default
